### ISSUE TITLE
feat: button colors

### ISSUE THREAD

**Issue by robertbaker** [nobitagit/ng-material-floating-button#18]
With angular-material, it would be nice to set custom classes on the menu and buttons. So each button could be a different color.

**Comment by nobitagit** [comment]
What's preventing you to make 

```html
<a mfb-button class="my-class" icon="share" label="menu"></a>
<a mfb-button class="my-other-class" icon="share" label="menu"></a>
```
And the then target each button via css? 
Or also just getting there via CSS pseudo class like:
```css
.mfb-component__list li:nth-child(1){
     background: teal;
}
```
