### ISSUE TITLE
Animation finished event [Enhancement]

### ISSUE THREAD

**Issue by fergusg** [nobitagit/ng-material-floating-button#36]
With my app the menu frequently appear over content (visually confusing) so my workaround is to fade the main content (`opacity: 20%`, say) while the menu is active via `main-action()`.  

This works great for the menu open, but ideally I'd like a way to un-fade the content **after**  the menu close animation is complete.  Something like an `onAnimationFinished` event, perhaps (though a full suite of `onMenuOpenStart`/ `onMenuOpenFinished`/ `onMenuClosedStart`/ `onMenuClosedFinished` events would be even cooler)

Thanks for a great widget.

**Comment by nobitagit** [comment]
Hi, that might actually be an interesting enhancement.

Anyway I think that with little trickery you can already achieve what you're after and have a smooth effect. If you conditionally apply a class like `fadeOut` to the whole element and attach it to the menu state you can easily control the opacity of the whole menu. Moreover you can decide that when closing the menu the fading is applied only after a certain delay.

For example:

- Set the element to something like this: 
```html
<nav mfb-menu class="app-menu" menu-state="menuState" 
     ng-class="{'fadeOut' : menuState === 'closed'}">
```
- in your stylesheets:
```css
.app-menu{
  opacity: 1;
  transition: opacity .9s; /* the menu fades IN at this speed */
}
.fadeOut{
  opacity: 0.3;
  transition: opacity .8s; /* the menu fades in OUT this speed */
  transition-delay: .5s; /* delay fading out the menu as much as we need*/
}
```

I made a quick [Plunkr](http://plnkr.co/edit/4eFxqSg21U5ZR5H59rdK?p=preview) for this. Hope this helps.
