### ISSUE TITLE
Child icons font-size

### ISSUE THREAD

**Issue by jayagl** [nobitagit/ng-material-floating-button#53]
It's a very small thing, but I thought I should mention it. 

There is no way to customise the size of the icons on child buttons without changing the whole button size, as it uses the `$child_button_size` variable 

```scss
.mfb-component__child-icon,
.mfb-component__child-icon{
  @extend .mfb-component__icon;
  line-height: $child_button_size;
  font-size: 18 / 56 * $child_button_size;
}
```
The existing sass variable `$icons-font-size` works well here,  but for some reason is not used here. Even though it looks like it should be. 

```scss
.mfb-component__child-icon,
.mfb-component__child-icon{
  @extend .mfb-component__icon;
  line-height: $child_button_size;
  font-size: $icons-font-size;
}
```
